name: create pr on template updates

on:
  repository_dispatch:
    types: [new-template-version]
  pull_request:
    types: [ labeled ]

jobs:
  create-pr-from-copier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install copier
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: apply copier template and save version
        run: |
          # grab pyfar version
          update_info=$(copier check-update --output-format json)
          latest_version=$(python -c "import json,sys; print(json.loads(sys.argv[1])['latest_version'])" "$update_info")
          echo "latest_version=$latest_version"

          # update copier
          copier update --overwrite yes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
            commit-message: apply copier template
            title: "[Bot]: apply copier template version ${{ env.latest_version }}"
            base: main
            body: |
              - apply latest changes from copier template version ${{ env.latest_version }}
            branch: template/copier-${{ env.latest_version }}
            draft: true
