name: Test DeprecationWarnings in Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13-dev"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements_dev.txt
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsndfile1
      - name: install pip dependencies
        run: pip install -r requirements_dev.txt
      - name: run test
        run: pytest tests -W error::DeprecationWarning
